[package]
name = "licheszter"
version = "0.1.0"
authors = ["tontsa28 <tontsadev@gmail.com>"]
license-file = "LICENSE"
description = "API wrapper for Lichess bot API"
homepage = "https://github.com/tontsa28/licheszter"
repository = "https://github.com/tontsa28/licheszter"
documentation = "https://docs.rs/licheszter"
keywords = ["lichess", "bot", "api", "wrapper", "chess"]
categories = ["api-bindings", "asynchronous"]
readme = "README.md"
edition = "2021"

[lib]
name = "licheszter"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.9", features = ["io-util"] }
tokio-util = { version = "0.7.3", features = ["io"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_with = "2.0.0"
thiserror = "1.0.32"
futures-util = "0.3.24"
bytes = "1.2.1"
