[package]
name = "licheszter"
version = "0.1.0"
authors = ["tontsa28 <tontsadev@gmail.com>"]
license-file = "LICENSE"
description = "API wrapper for Lichess bot API"
homepage = "https://github.com/tontsa28/licheszter"
repository = "https://github.com/tontsa28/licheszter"
documentation = "https://docs.rs/licheszter"
keywords = ["lichess", "bot", "api", "wrapper", "chess"]
categories = ["api-bindings", "asynchronous"]
readme = "README.md"
edition = "2021"

[lib]
name = "licheszter"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio-util = { version = "0.7.8", features = ["io"] }
reqwest = { version = "0.11.17", default-features = false, features = ["json", "stream", "rustls-tls"] }
chrono = { version = "0.4.24", features = ["serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "3.0.0"
thiserror = "1.0.40"
futures-util = "0.3.28"

[features]
explorer = []
tablebase = []
