[package]
name = "licheszter"
version = "0.1.0"
authors = ["tontsa28 <miika@tontsa.fi>"]
license = "MIT OR Apache-2.0"
description = "An API wrapper for the Lichess API"
homepage = "https://github.com/tontsa28/licheszter"
repository = "https://github.com/tontsa28/licheszter"
documentation = "https://docs.rs/licheszter"
keywords = ["lichess", "bot", "api", "wrapper", "chess"]
categories = ["api-bindings", "asynchronous"]
readme = "README.md"
edition = "2021"

[lib]
name = "licheszter"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.38.0"
tokio-stream = { version = "0.1.15", default-features = false, features = ["io-util"] }
tokio-util = "0.7.11"
reqwest = { version = "0.12.4", default-features = false, features = ["stream", "rustls-tls"] }
time = { version = "0.3.36", features = [] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_with = { version = "3.8.1", features = ["time_0_3"] }
futures-util = { version = "0.3.30", default-features = false }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["macros"] }
wiremock = "0.6.0"

[features]
# No features are enabled by default
default = []

# Return an error when an unknown field is encountered while deserializing
# This is not recommended for production environments as it might cause unexpected problems
serde-strict = []

explorer = []
tablebase = []
