[package]
name = "licheszter"
version = "0.1.0"
authors = ["tontsa28 <tontsadev@gmail.com>"]
license = "AGPL v3.0"
description = "API wrapper for Lichess bot API"
repository = "https://github.com/tontsa28/licheszter"
keywords = ["lichess", "bot", "api", "wrapper", "chess", "licheszter", "cheszter"]
categories = ["api-bindings", "asynchronous"]
readme = "README.md"
edition = "2021"

[lib]
name = "licheszter"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
opt-level = 0

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.9", features = ["io-util"] }
tokio-util = { version = "0.7.3", features = ["io"] }
reqwest = { version = "0.11.10", features = ["json", "stream"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_with = "1.14.0"
thiserror = "1.0.31"
futures-util = "0.3.21"
bytes = "1.1.0"
