name: licheszter integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: --restart=always --name lila
        ports:
          - 8080:9663
    steps:
      - uses: actions/checkout@v3

      - name: Run all integration tests
        run: cargo test --release --features=serde-strict,all -- --test-threads=1