name: licheszter integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 18 * * 6'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:slim
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: -p 8080:9663 --restart=always --name lila
    steps:
      - uses: actions/checkout@v3

      - name: Install cURL
        run: apt update && apt install curl -y

      - name: Check if the container is running
        run: /usr/bin/docker ps

      - name: Print container logs
        run: /usr/bin/docker logs lila

      - name: Sleep for a bit
        run: sleep 30s

      - name: Test the backend
        run: 'curl -H "Authorization: Bearer lip_li" http://localhost:8080/api/challenge/Bot0 -d ""'

      - name: Check the project
        run: cargo test --release --features=serde-strict,all -- --test-threads=1