name: licheszter integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:sid-slim
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: --restart=always
    steps:
      - uses: actions/checkout@v3

      - name: Update toolchain
        run: rustup update

      - name: Check the project
        run: cargo test --features=dev -- --test-threads=1