name: licheszter integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:slim
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: --restart=always
    steps:
      - uses: actions/checkout@v3

      - name: Check the project
        run: cargo test --features=serde-strict,all -- --test-threads=1