name: licheszter integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: --restart=always --name lila
        ports:
          - 8080:8080
      lila-bots:
        image: python:latest
        options: -t --name lila-bots --entrypoint "/bin/sh"

    steps:
      - uses: actions/checkout@v4

      - name: Connect to bot accounts
        run: docker cp ${{ github.workspace }}/.github/docker/entrypoint.sh lila-bots:/entrypoint.sh && docker exec -d lila-bots ./entrypoint.sh && sleep 5s

      - name: Run all integration tests
        run: cargo test --release --features=serde-strict,all -- --test-threads=1